### ISSUE TITLE
Examples Provided

### ISSUE THREAD

**Issue by krital** [SignalK/signalk-apple-client#1]
Hi there,

thanks for your great efforts. I have managed to compile and run both obj-c and swift examples but when I point them to an iKommunicate with latest firmware (2018060100) they both give me a pop up dialog saying: Error Connecting: Unable to determine self

Any ideas on how this could be resolved?

Thanks,

Alex

**Comment by sbender9** [comment]
Are you running the latest iK firmware? I don't get that error when connecting to my iK.

**Comment by krital** [comment]
My understanding is that this is the latest firmware, at least the iK admin page says so. What firmware are you running exactly?

**Comment by sbender9** [comment]
Mine says version: 2018060100

Make sure you have the latest code, I think I remember this being an issue a long time ago.

Then put a breakpoint here https://github.com/SignalK/signalk-apple-client/blob/master/SignalKClient/Classes/SignalK.m#L335

And take a look at what the error is.

**Comment by sbender9** [comment]
Do you have the mmsi set in the Configuration? That could be the issue.

**Comment by krital** [comment]
That was it! Set the MMSI to 0 and it all worked. Thanks for your help
