### ISSUE TITLE
Problem with context in "- (void)callDelegates:(NSDictionary *)delta"

### ISSUE THREAD

**Issue by cbo1964** [SignalK/signalk-apple-client#2]
Hi,

thanks for the library but I found a problem.
I just downloaded your project, compiled and run using an iK.
I saw that the [self.signalK registerSKDelegate:self.windAngle forPath:@"environment.wind.angleTrueGround"]; it is not causing the call the windAngle delegate.

I debug and what I found is that in the - (void)callDelegates:(NSDictionary *)delta you have this if (line 941):
			if ( (info.path == nil || [path isEqualToString:info.path])
				&& (
                    info.context == nil
                    || ([info.context isEqualToString:@"vessels.self"] && [context isEqualToString:self.selfContext])
                    || [info.context isEqualToString:context]
                    ) )

but as you can see from these log:

Printing description of self->_selfContext:
urn:mrn:imo:mmsi:15081964
Printing description of context:
vessels.urn:mrn:imo:mmsi:15081964
   
context it is NOT equal to self.selfContext due to the "vessels" component path in front of it.

I suppose this is a small bug somewhere that you can easily fix, in fact my question is wider, how much this library has been tested ? I'm going to use for a commercial project and founding a bug just as I started is worrying me a little bit. I know that developers (I'm a developer) does not like this question but I have to make it.

Thanks
Claudio

**Comment by sbender9** [comment]
Thanks Claudio, looks like a simple bug I'll get fixed ASAP.

This library is used by my commercial app WilhelmSK, much if the library is very well tested. It happens to be that WilhelmSK does not use this feature, so the issue was not caught with testing there.

I'll do some more testing the the iKommunicate and make everything works.

Just note that the iKummunicate is not very spec compliant at this time, so some things like `subscribe=none` and then sending individual; subscriptions via WS does not work.

**Comment by cbo1964** [comment]
Hi Scott,

maybe you could add in the library that if the signalK device does not accept the subscription=none then you can try again with "self".

What do you think ?

Claudio

**Comment by sbender9** [comment]
I would not want to do this in the library. Because things would not be working as the developer would expect.

I would (and do myself) handle this on the app side.

**Comment by sbender9** [comment]
I released 1.4.0 which has a fix for the selfContext being wrong with the iK

**Comment by cbo1964** [comment]
> I would not want to do this in the library. Because things would not be working as the developer would expect.
> 
> I would (and do myself) handle this on the app side.

ok I understand .. correct
