### ISSUE TITLE
getWSURL

### ISSUE THREAD

**Issue by cbo1964** [SignalK/signalk-apple-client#3]
Hi,

in the getWSURL you have:
NSString *urlS = [NSString stringWithFormat:@"%@?stream=delta&subscribe=%@", self.wsEndpoint, subsciption];
    
but accordingly to the current documentation should be:
 NSString *urlS = [NSString stringWithFormat:@"%@?subscribe=%@", self.wsEndpoint, subsciption];

Is it true ? Keep in mind I have not previous experience on SignalK so maybe this is a change in the specs. The problem is that with current iKommunicate if I use your library and I give "none" as subscription value does not work (error 501)

Thanks
Claudio

**Comment by sbender9** [comment]
You're correct that `stream=delta` should not be there and I will remove it.

But the real issue here is that the iKommunicate does not support `subscribe=none`:

```
> $ wscat -n -c 'ws://192.168.1.124/signalk/v1/stream?subscribe=none'
error: Unexpected server response: 501
```

Looks like it only supports `all` or `none`

**Comment by cbo1964** [comment]
Hi Scott,

many thanks (for the library and your time).

I understand but I have a doubt.
If I would have just the data I need, it is suggested to start with subscription=none and then subscribe to specific data.
How could I do this with the iKommunicate ?

Best Regards
Claudio

**Comment by sbender9** [comment]
Yes, that's how you should do it per the spec. And that works fine with node server and the java server.

But with iKommunicate , all you can do is subscribe to self and then filter the incoming deltas.

**Comment by cbo1964** [comment]
> Yes, that's how you should do it per the spec. And that works fine with node server and the java server.
> 
> But with iKommunicate , all you can do is subscribe to self and then filter the incoming deltas.

ok understand .. clear
