### ISSUE TITLE
Background work

### ISSUE THREAD

**Issue by cbo1964** [SignalK/signalk-apple-client#4]
Hi,

is there a way to have the App continue to receive signalK messages even if in background mode ?

Regards

**Comment by sbender9** [comment]
My understanding is that Apple does not let you do much in the background and you definitely can't rely on it. The iOS can kill your app at any time.IMHO,  it's best to leave important background work (like an anchor alarm, for example) to be done on the server side.

**Comment by cbo1964** [comment]
Hi Scott,

But if I would the alarm to appear on the phone while sleeping I have in any case to receive the alarm from the server, so the problem is still there.

Claudio
